import type { LibraryWorkout, Block, Step } from "./types";

const S = (
  secs: number,
  lo: number,
  hi: number,
  x: Partial<Step> = {}
): Step => ({
  secs,
  lo,
  hi,
  ...x,
});
const B = (name: string, repeat: number, steps: Step[]): Block => ({
  name,
  repeat,
  steps,
});
/** Warmup ramps; it is the flex step for quality sessions. */
const WU = (m: number) => B("Warmup", 1, [S(m * 60, 50, 70, { ramp: true })]);
const CD = (m: number) => B("Cooldown", 1, [S(m * 60, 50, 50)]);
/** The endurance body — the flex step for recovery, aerobic_base and long. */
const BODY = (m: number, lo: number, hi: number) =>
  B("Endurance", 1, [S(m * 60, lo, hi)]);

/** `source` in the shape plan-constants.ts uses. */
const conv = (what: string, raise: string): string =>
  `Coaching convention. Confidence: Low — ${what}. What would raise it: ${raise}.`;

const NO_TRIAL =
  "a controlled comparison of these block lengths at this intensity on the same athlete";

/**
 * The curated cycling library. Hand-authored, and the reason this feature
 * reverses a recorded non-goal — see the spec's "The reversal, recorded".
 *
 * Every workout carries a `source` naming its provenance, a confidence label,
 * and what would raise it. They are coaching conventions and they say so; a
 * shape dressed up as a citation it does not have would break the admission
 * gate the whole reversal rests on.
 *
 * Ids are stable and never renumbered — selection sorts on them.
 */
export const LIBRARY: readonly LibraryWorkout[] = [
  // ── recovery ─────────────────────────────────────────────────────────
  {
    id: "rec-spin-30",
    name: "Recovery Spin",
    purpose: "recovery",
    family: "easy-spin",
    why: "Turn the legs over; nothing more.",
    source: conv(
      "no trial fixes a recovery ride's length",
      "any evidence that duration matters below the aerobic threshold"
    ),
    blocks: [WU(5), BODY(20, 45, 55), CD(5)],
  },
  {
    id: "rec-spin-70",
    name: "Long Easy Spin",
    purpose: "recovery",
    family: "easy-spin",
    why: "A longer easy ride when the plan wants volume without stress.",
    source: conv("as rec-spin-30", "the same"),
    blocks: [WU(5), BODY(60, 45, 55), CD(5)],
  },
  {
    id: "rec-cadence-30",
    name: "Recovery with Cadence",
    purpose: "recovery",
    family: "cadence-play",
    why: "Easy effort at high cadence — neuromuscular work without load.",
    source: conv(
      "high-cadence spinning on recovery days is convention, untested against plain easy riding",
      "a trial comparing recovery quality with and without the cadence work"
    ),
    blocks: [WU(5), B("Easy", 1, [S(1200, 45, 55, { rpm: 95 })]), CD(5)],
  },
  {
    id: "rec-cadence-70",
    name: "Long Recovery with Cadence",
    purpose: "recovery",
    family: "cadence-play",
    why: "As the short version, stretched.",
    source: conv("as rec-cadence-30", "the same"),
    blocks: [WU(5), B("Easy", 1, [S(3600, 45, 55, { rpm: 95 })]), CD(5)],
  },

  // ── aerobic_base ─────────────────────────────────────────────────────
  {
    id: "end-short",
    name: "Short Endurance",
    purpose: "aerobic_base",
    family: "endurance",
    why: "Steady aerobic riding — the plan's default session.",
    source: conv(
      "zone-2 riding is near-universal convention; its exact band is not settled",
      "a comparison of 56-75% against a narrower band on the same athlete"
    ),
    blocks: [WU(6), BODY(15, 56, 75), CD(6)],
  },
  {
    id: "end-mid",
    name: "Endurance",
    purpose: "aerobic_base",
    family: "endurance",
    why: "Steady aerobic riding.",
    source: conv("as end-short", "the same"),
    blocks: [WU(6), BODY(30, 56, 75), CD(6)],
  },
  {
    id: "end-long",
    name: "Endurance, Extended",
    purpose: "aerobic_base",
    family: "endurance",
    why: "Steady aerobic riding at length.",
    source: conv("as end-short", "the same"),
    blocks: [WU(10), BODY(75, 56, 75), CD(10)],
  },
  {
    id: "end-xl",
    name: "Endurance, Long",
    purpose: "aerobic_base",
    family: "endurance",
    why: "The upper end of an endurance day.",
    source: conv("as end-short", "the same"),
    blocks: [WU(10), BODY(210, 56, 72), CD(10)],
  },
  {
    id: "end-tempo-mid",
    name: "Endurance with Tempo",
    purpose: "aerobic_base",
    family: "tempo-touches",
    why: "Aerobic volume with two tempo blocks for shape.",
    source: conv(
      "tempo touches inside an endurance ride are convention for time-limited weeks",
      "a comparison against the same minutes ridden flat"
    ),
    blocks: [
      WU(10),
      BODY(30, 56, 72),
      B("Tempo", 2, [S(600, 76, 83), S(300, 55, 55)]),
      CD(10),
    ],
  },
  {
    id: "end-tempo-long",
    name: "Endurance with Tempo, Extended",
    purpose: "aerobic_base",
    family: "tempo-touches",
    why: "As above, longer.",
    source: conv("as end-tempo-mid", "the same"),
    blocks: [
      WU(10),
      BODY(75, 56, 72),
      B("Tempo", 3, [S(600, 76, 83), S(300, 55, 55)]),
      CD(10),
    ],
  },

  // ── long ─────────────────────────────────────────────────────────────
  {
    id: "long-short",
    name: "Short Long Ride",
    purpose: "long",
    family: "long-steady",
    why: "The shortest ride the plan still calls long.",
    source: conv(
      "the two-hour convention for endurance rides is uncited coaching guidance, already recorded at MIN_LONG_BOUND_MINS",
      "a dose-response study on ride duration in trained cyclists"
    ),
    blocks: [WU(10), BODY(40, 56, 72), CD(10)],
  },
  {
    id: "long-mid",
    name: "Long Ride",
    purpose: "long",
    family: "long-steady",
    why: "Steady aerobic hours.",
    source: conv("as long-short", "the same"),
    blocks: [WU(15), BODY(90, 56, 72), CD(15)],
  },
  {
    id: "long-xl",
    name: "Long Ride, Extended",
    purpose: "long",
    family: "long-steady",
    why: "The long end of a long ride.",
    source: conv("as long-short", "the same"),
    blocks: [WU(15), BODY(210, 56, 70), CD(15)],
  },
  {
    id: "long-surges-mid",
    name: "Long Ride with Surges",
    purpose: "long",
    family: "long-surges",
    why: "Steady hours with short efforts late, on already-tired legs.",
    source: conv(
      "late-ride efforts to rehearse fatigue resistance are convention; the placement is not derived",
      "a trial placing the same efforts early against late"
    ),
    blocks: [
      WU(15),
      BODY(90, 56, 72),
      B("Surges", 4, [S(60, 105, 115), S(240, 55, 65)]),
      CD(15),
    ],
  },
  {
    id: "long-surges-xl",
    name: "Long Ride with Surges, Extended",
    purpose: "long",
    family: "long-surges",
    why: "As above, longer.",
    source: conv("as long-surges-mid", "the same"),
    blocks: [
      WU(15),
      BODY(180, 56, 70),
      B("Surges", 5, [S(60, 105, 115), S(240, 55, 65)]),
      CD(15),
    ],
  },

  // ── threshold ────────────────────────────────────────────────────────
  {
    id: "thr-3x4",
    name: "Threshold 3×4",
    purpose: "threshold",
    family: "threshold-blocks",
    why: "Three short blocks at threshold — the shortest session that still delivers the stimulus.",
    // The 4-minute cooldown is deliberate: FLEX_FLOOR_SECS stops the warmup
    // shrinking below 5 minutes, so a 5-minute cooldown would start this
    // workout's span at 28 and leave the 27-minute day unanswered.
    source: conv(
      "block length at threshold is convention, not derived",
      NO_TRIAL
    ),
    blocks: [WU(8), B("Main set", 3, [S(240, 95, 100), S(120, 55, 55)]), CD(4)],
  },
  {
    id: "thr-3x5",
    name: "Threshold 3×5",
    purpose: "threshold",
    family: "threshold-blocks",
    why: "Three blocks at threshold.",
    source: conv("as thr-3x4", NO_TRIAL),
    blocks: [
      WU(10),
      B("Main set", 3, [S(300, 95, 100), S(180, 55, 55)]),
      CD(6),
    ],
  },
  {
    id: "ss-3x5",
    name: "Sweet Spot 3×5",
    purpose: "threshold",
    family: "sweet-spot",
    why: "Three short sweet-spot blocks — less sharp than threshold, easier to repeat.",
    source: conv(
      "the sweet-spot band (88-93%) is widely used and has no settled definition",
      "a comparison of 88-93% against 95-100% for the same total work"
    ),
    blocks: [WU(10), B("Main set", 3, [S(300, 88, 93), S(180, 55, 55)]), CD(6)],
  },
  {
    id: "thr-3x5-long-wu",
    name: "Threshold 3×5, Long Build",
    purpose: "threshold",
    family: "threshold-blocks",
    why: "The same main set behind a longer build.",
    source: conv("as thr-3x4", NO_TRIAL),
    blocks: [
      WU(20),
      B("Main set", 3, [S(300, 95, 100), S(180, 55, 55)]),
      CD(6),
    ],
  },
  {
    id: "ss-2x12",
    name: "Sweet Spot 2×12",
    purpose: "threshold",
    family: "sweet-spot",
    why: "Two longer sweet-spot blocks.",
    source: conv("as ss-3x5", "the same"),
    blocks: [WU(20), B("Main set", 2, [S(720, 88, 93), S(300, 55, 55)]), CD(8)],
  },
  {
    id: "thr-4x8",
    name: "Threshold 4×8",
    purpose: "threshold",
    family: "threshold-blocks",
    why: "Four blocks at threshold — the classic mid-length session.",
    source: conv("as thr-3x4", NO_TRIAL),
    blocks: [
      WU(25),
      B("Main set", 4, [S(480, 95, 100), S(240, 55, 55)]),
      CD(9),
    ],
  },
  {
    id: "ou-3x12",
    name: "Over-Under 3×12",
    purpose: "threshold",
    family: "over-under",
    why: "Alternating either side of threshold — clearing lactate while still working.",
    source: conv(
      "over-unders are convention for threshold tolerance; the 2-minute alternation is arbitrary",
      "a trial comparing alternation periods at matched total work"
    ),
    blocks: [
      WU(25),
      B("Main set", 3, [
        S(120, 105, 105),
        S(120, 90, 90),
        S(120, 105, 105),
        S(120, 90, 90),
        S(120, 105, 105),
        S(120, 90, 90),
        S(300, 55, 55),
      ]),
      CD(9),
    ],
  },
  {
    id: "ss-3x20",
    name: "Sweet Spot 3×20",
    purpose: "threshold",
    family: "sweet-spot",
    why: "Three long sweet-spot blocks — the upper end of a threshold day.",
    source: conv("as ss-3x5", "the same"),
    blocks: [
      WU(28),
      B("Main set", 3, [S(1200, 88, 93), S(300, 55, 55)]),
      CD(9),
    ],
  },

  // ── vo2max ───────────────────────────────────────────────────────────
  {
    id: "vo2-6x1",
    name: "VO₂max 6×1",
    purpose: "vo2max",
    family: "short-vo2",
    why: "Six short, sharp efforts — the shortest VO₂max session worth doing.",
    source: conv(
      "short-interval VO2max work is convention; one minute is one of several lengths in use",
      "a comparison of 1-, 3- and 5-minute intervals at matched total work"
    ),
    blocks: [
      WU(16),
      B("Main set", 6, [S(60, 110, 120), S(120, 50, 50)]),
      CD(6),
    ],
  },
  {
    id: "vo2-5x3",
    name: "VO₂max 5×3",
    purpose: "vo2max",
    family: "classic-vo2",
    why: "Five three-minute efforts with equal recovery.",
    source: conv("3-minute intervals at 106-118% are convention", NO_TRIAL),
    blocks: [
      WU(20),
      B("Main set", 5, [S(180, 106, 118), S(180, 50, 50)]),
      CD(8),
    ],
  },
  {
    id: "vo2-30-30",
    name: "VO₂max 30/30",
    purpose: "vo2max",
    family: "short-vo2",
    why: "Thirty on, thirty off — accumulates time near VO₂max at lower perceived cost.",
    source: conv(
      "30/30s are widely used; the claim that they accumulate more time at VO2max is not tested here",
      "a comparison of measured time-at-VO2max against 4-minute intervals"
    ),
    blocks: [
      WU(20),
      B("Main set", 3, [
        S(30, 115, 125),
        S(30, 50, 50),
        S(30, 115, 125),
        S(30, 50, 50),
        S(30, 115, 125),
        S(30, 50, 50),
        S(30, 115, 125),
        S(30, 50, 50),
        S(30, 115, 125),
        S(30, 50, 50),
        S(300, 50, 50),
      ]),
      CD(8),
    ],
  },
  {
    id: "vo2-5x4",
    name: "VO₂max 5×4",
    purpose: "vo2max",
    family: "classic-vo2",
    why: "Five four-minute efforts — the session most plans mean by VO₂max.",
    source: conv("as vo2-5x3", NO_TRIAL),
    blocks: [
      WU(25),
      B("Main set", 5, [S(240, 106, 115), S(240, 50, 50)]),
      CD(9),
    ],
  },
  {
    id: "vo2-4x5",
    name: "VO₂max 4×5",
    purpose: "vo2max",
    family: "classic-vo2",
    why: "Four five-minute efforts — longer and a little lower than 5×4.",
    source: conv("as vo2-5x3", NO_TRIAL),
    blocks: [
      WU(30),
      B("Main set", 4, [S(300, 106, 112), S(300, 50, 50)]),
      CD(9),
    ],
  },
  {
    id: "vo2-8x3",
    name: "VO₂max 8×3",
    purpose: "vo2max",
    family: "short-vo2",
    why: "Eight three-minute efforts.",
    source: conv("as vo2-6x1", "the same"),
    blocks: [
      WU(30),
      B("Main set", 8, [S(180, 108, 116), S(180, 50, 50)]),
      CD(9),
    ],
  },
  {
    id: "vo2-12x3",
    name: "VO₂max 12×3",
    purpose: "vo2max",
    family: "short-vo2",
    why: "Twelve three-minute efforts — the upper end of a VO₂max day.",
    source: conv("as vo2-6x1", "the same"),
    blocks: [
      WU(26),
      B("Main set", 12, [S(180, 108, 116), S(180, 50, 50)]),
      CD(9),
    ],
  },

  // ── slice 5: a second family at every covered duration ───────────────
  // Thirty workouts tiled every range but left about half the covered
  // minutes with a single family, so `matchWorkout`'s family-first pick had
  // nothing to choose between and the same day drew the same session. These
  // sixteen were authored against the measured gaps rather than to a target
  // count: 21-64, 96-102 and 178-210 for aerobic_base, 48-94 for long,
  // 27-34/46-51/61-69/95-120 for threshold, 32-47/69-71/95-120 for vo2max.
  {
    id: "end-cadence-short",
    name: "Short Endurance, High Cadence",
    purpose: "aerobic_base",
    family: "cadence-endurance",
    why: "Steady aerobic riding held at a deliberately high cadence.",
    source: conv(
      "riding endurance at a raised cadence is a long-standing convention for neuromuscular economy; the claim is not tested here and the 95rpm figure is a round number",
      "a comparison of matched endurance minutes ridden at self-selected versus prescribed cadence"
    ),
    blocks: [WU(6), B("Endurance", 1, [S(1080, 56, 72, { rpm: 95 })]), CD(6)],
  },
  {
    id: "end-cadence-mid",
    name: "Endurance, High Cadence",
    purpose: "aerobic_base",
    family: "cadence-endurance",
    why: "As the short version, at a normal endurance length.",
    source: conv("as end-cadence-short", "the same"),
    blocks: [WU(6), B("Endurance", 1, [S(2700, 56, 72, { rpm: 95 })]), CD(6)],
  },
  {
    id: "end-cadence-long",
    name: "Endurance, High Cadence, Extended",
    purpose: "aerobic_base",
    family: "cadence-endurance",
    why: "As above, longer.",
    source: conv("as end-cadence-short", "the same"),
    blocks: [WU(6), B("Endurance", 1, [S(4200, 56, 72, { rpm: 95 })]), CD(6)],
  },
  {
    id: "end-cadence-xl",
    name: "Long Endurance, High Cadence",
    purpose: "aerobic_base",
    family: "cadence-endurance",
    why: "The upper end of an endurance day, at cadence.",
    source: conv("as end-cadence-short", "the same"),
    blocks: [WU(6), B("Endurance", 1, [S(9000, 56, 70, { rpm: 95 })]), CD(6)],
  },
  {
    id: "long-surges-short",
    name: "Short Long Ride with Surges",
    purpose: "long",
    family: "long-surges",
    why: "The shortest long ride that still finishes with efforts on tired legs.",
    source: conv("as long-surges-mid", "the same"),
    blocks: [
      WU(10),
      BODY(25, 56, 72),
      B("Surges", 2, [S(60, 105, 115), S(240, 55, 65)]),
      CD(10),
    ],
  },
  {
    id: "long-surges-mid2",
    name: "Long Ride with Surges, Short Build",
    purpose: "long",
    family: "long-surges",
    why: "The same shape as the mid-length version, over fewer hours.",
    source: conv("as long-surges-mid", "the same"),
    blocks: [
      WU(15),
      BODY(40, 56, 72),
      B("Surges", 3, [S(60, 105, 115), S(240, 55, 65)]),
      CD(15),
    ],
  },
  {
    id: "ss-3x4",
    name: "Sweet Spot 3×4",
    purpose: "threshold",
    family: "sweet-spot",
    why: "The shortest sweet-spot session worth clipping in for.",
    // Same 4-minute cooldown as thr-3x4, and for the same reason:
    // FLEX_FLOOR_SECS stops an 8-minute warmup shrinking below 5.
    source: conv("as ss-3x5", "the same"),
    blocks: [WU(8), B("Main set", 3, [S(240, 88, 93), S(120, 55, 55)]), CD(4)],
  },
  {
    id: "ss-2x8",
    name: "Sweet Spot 2×8",
    purpose: "threshold",
    family: "sweet-spot",
    why: "Two mid-length sweet-spot blocks.",
    source: conv("as ss-3x5", "the same"),
    blocks: [WU(15), B("Main set", 2, [S(480, 88, 93), S(240, 55, 55)]), CD(6)],
  },
  {
    id: "thr-4x6",
    name: "Threshold 4×6",
    purpose: "threshold",
    family: "threshold-blocks",
    why: "Four shorter blocks at threshold.",
    source: conv("as thr-3x4", NO_TRIAL),
    blocks: [
      WU(20),
      B("Main set", 4, [S(360, 95, 100), S(180, 55, 55)]),
      CD(8),
    ],
  },
  {
    id: "thr-4x9",
    name: "Threshold 4×9",
    purpose: "threshold",
    family: "threshold-blocks",
    why: "Four blocks at threshold, a notch longer than 4×8.",
    source: conv("as thr-3x4", NO_TRIAL),
    blocks: [
      WU(25),
      B("Main set", 4, [S(540, 95, 100), S(240, 55, 55)]),
      CD(9),
    ],
  },
  {
    id: "thr-5x10",
    name: "Threshold 5×10",
    purpose: "threshold",
    family: "threshold-blocks",
    why: "Five long blocks at threshold — the upper end of the session.",
    source: conv("as thr-3x4", NO_TRIAL),
    blocks: [
      WU(25),
      B("Main set", 5, [S(600, 95, 100), S(300, 55, 55)]),
      CD(9),
    ],
  },
  {
    id: "ou-4x12",
    name: "Over-Under 4×12",
    purpose: "threshold",
    family: "over-under",
    why: "A fourth over-under block, for a longer threshold day.",
    source: conv("as ou-3x12", "the same"),
    blocks: [
      WU(25),
      B("Main set", 4, [
        S(120, 105, 105),
        S(120, 90, 90),
        S(120, 105, 105),
        S(120, 90, 90),
        S(120, 105, 105),
        S(120, 90, 90),
        S(300, 55, 55),
      ]),
      CD(9),
    ],
  },
  {
    id: "vo2-3x3",
    name: "VO₂max 3×3",
    purpose: "vo2max",
    family: "classic-vo2",
    why: "Three three-minute efforts — a short introduction to the session.",
    source: conv("as vo2-5x3", NO_TRIAL),
    blocks: [
      WU(10),
      B("Main set", 3, [S(180, 106, 118), S(180, 50, 50)]),
      CD(5),
    ],
  },
  {
    id: "vo2-4x3",
    name: "VO₂max 4×3",
    purpose: "vo2max",
    family: "classic-vo2",
    why: "Four three-minute efforts with equal recovery.",
    source: conv("as vo2-5x3", NO_TRIAL),
    blocks: [
      WU(12),
      B("Main set", 4, [S(180, 106, 118), S(180, 50, 50)]),
      CD(6),
    ],
  },
  {
    id: "vo2-40-20",
    name: "VO₂max 40/20",
    purpose: "vo2max",
    family: "short-vo2",
    why: "Forty on, twenty off — a harder cousin of the 30/30.",
    source: conv(
      "40/20s are a widely used variant of the same convention as 30/30s; nothing here tests whether the longer on-interval changes the stimulus",
      "a comparison of measured time-at-VO2max between 40/20 and 30/30 at matched total work"
    ),
    blocks: [
      WU(20),
      B("Main set", 3, [
        S(40, 115, 125),
        S(20, 50, 50),
        S(40, 115, 125),
        S(20, 50, 50),
        S(40, 115, 125),
        S(20, 50, 50),
        S(40, 115, 125),
        S(20, 50, 50),
        S(40, 115, 125),
        S(20, 50, 50),
        S(40, 115, 125),
        S(20, 50, 50),
        S(40, 115, 125),
        S(20, 50, 50),
        S(40, 115, 125),
        S(20, 50, 50),
        S(300, 50, 50),
      ]),
      CD(8),
    ],
  },
  {
    id: "vo2-6x5-long-wu",
    name: "VO₂max 6×5, Long Build",
    purpose: "vo2max",
    family: "classic-vo2",
    why: "Six five-minute efforts behind a long build — the longest VO₂max day.",
    source: conv("as vo2-5x3", NO_TRIAL),
    blocks: [
      WU(35),
      B("Main set", 6, [S(300, 106, 112), S(300, 50, 50)]),
      CD(9),
    ],
  },

  // ── slice 5: the library to 100+ ─────────────────────────────────────
  // Authored against the MEASURED thin bands, not to a round number. Before
  // this, every purpose sat at the two-family floor across most of its range
  // — recovery, long and vo2max at exactly two everywhere — so the rotation
  // machinery had a choice of two and the same day drew from the same pair.
  // Each family below is a distinct STIMULUS, because that is what rotation
  // keys on; a fourth name for the same shape would not be variety.

  // recovery: two families answered every minute. These make it four.
  {
    id: "rec-single-25",
    name: "Recovery with Single-Leg Drills",
    purpose: "recovery",
    family: "single-leg",
    why: "Easy riding with isolated-leg work — pedalling mechanics at no metabolic cost.",
    source: conv(
      "isolated-leg drills are a long-standing coaching convention for pedal-stroke mechanics, and the transfer to whole-leg pedalling is not established",
      "a trial measuring pedal-stroke smoothness or economy after a drill block against plain easy riding"
    ),
    blocks: [
      WU(4),
      B("Single-leg drills", 3, [S(60, 50, 60, { rpm: 70 }), S(60, 50, 60)]),
      BODY(10, 45, 55),
      CD(5),
    ],
  },
  {
    id: "rec-single-45",
    name: "Recovery with Single-Leg Drills, Extended",
    purpose: "recovery",
    family: "single-leg",
    why: "The same drills in front of a longer easy ride.",
    source: conv("as rec-single-25", "the same"),
    blocks: [
      WU(4),
      B("Single-leg drills", 3, [S(60, 50, 60, { rpm: 70 }), S(60, 50, 60)]),
      BODY(30, 45, 55),
      CD(5),
    ],
  },
  {
    id: "rec-single-75",
    name: "Long Recovery with Single-Leg Drills",
    purpose: "recovery",
    family: "single-leg",
    why: "Drills early, then an hour of easy riding.",
    source: conv("as rec-single-25", "the same"),
    blocks: [
      WU(4),
      B("Single-leg drills", 3, [S(60, 50, 60, { rpm: 70 }), S(60, 50, 60)]),
      BODY(60, 45, 55),
      CD(5),
    ],
  },
  {
    id: "rec-openers-25",
    name: "Openers",
    purpose: "recovery",
    family: "openers",
    why: "A few short efforts on an otherwise easy ride — the day-before-a-race primer.",
    source: conv(
      "pre-race openers are near-universal practice and the protocol varies with every coach who prescribes one",
      "a controlled comparison of opener protocols against complete rest on next-day performance"
    ),
    blocks: [
      WU(4),
      B("Openers", 2, [S(60, 95, 105), S(120, 45, 55)]),
      BODY(10, 45, 55),
      CD(5),
    ],
  },
  {
    id: "rec-openers-45",
    name: "Openers, Extended",
    purpose: "recovery",
    family: "openers",
    why: "The same primers with more easy riding behind them.",
    source: conv("as rec-openers-25", "the same"),
    blocks: [
      WU(4),
      B("Openers", 2, [S(60, 95, 105), S(120, 45, 55)]),
      BODY(30, 45, 55),
      CD(5),
    ],
  },
  {
    id: "rec-openers-75",
    name: "Long Openers",
    purpose: "recovery",
    family: "openers",
    why: "Primers early, then a long easy spin.",
    source: conv("as rec-openers-25", "the same"),
    blocks: [
      WU(4),
      B("Openers", 2, [S(60, 95, 105), S(120, 45, 55)]),
      BODY(60, 45, 55),
      CD(5),
    ],
  },

  // aerobic_base: 21-64, 96-102 and 178-210 each had only two families.
  {
    id: "end-prog-short",
    name: "Progressive Endurance",
    purpose: "aerobic_base",
    family: "progressive",
    why: "Steady, then a stronger finish — the ride gets harder as it goes.",
    source: conv(
      "the negative-split endurance ride is convention; nothing here establishes that finishing stronger adapts differently from the same work ridden flat",
      "a trial comparing a progressive ride against a steady one of equal load"
    ),
    blocks: [
      WU(4),
      B("Steady", 1, [S(600, 55, 65)]),
      B("Build", 1, [S(300, 65, 75)]),
      CD(4),
    ],
  },
  {
    id: "end-prog-mid",
    name: "Progressive Endurance, Extended",
    purpose: "aerobic_base",
    family: "progressive",
    why: "A longer steady portion before the same stronger finish.",
    source: conv("as end-prog-short", "the same"),
    blocks: [
      WU(5),
      B("Steady", 1, [S(900, 55, 65)]),
      B("Build", 1, [S(600, 65, 75)]),
      CD(5),
    ],
  },
  {
    id: "end-prog-long",
    name: "Progressive Endurance, Long",
    purpose: "aerobic_base",
    family: "progressive",
    why: "An hour that finishes at the top of the aerobic range.",
    source: conv("as end-prog-short", "the same"),
    blocks: [
      WU(8),
      B("Steady", 1, [S(1500, 55, 65)]),
      B("Build", 1, [S(900, 65, 75)]),
      CD(6),
    ],
  },
  {
    id: "end-prog-xl",
    name: "Progressive Endurance, Extended Long",
    purpose: "aerobic_base",
    family: "progressive",
    why: "Two hours with the last half-hour lifted.",
    source: conv("as end-prog-short", "the same"),
    blocks: [
      WU(10),
      B("Steady", 1, [S(3300, 55, 65)]),
      B("Build", 1, [S(1200, 65, 75)]),
      CD(8),
    ],
  },
  {
    id: "end-prog-xxl",
    name: "Progressive Endurance, Longest",
    purpose: "aerobic_base",
    family: "progressive",
    why: "The longest progressive ride the plan will ask for.",
    source: conv("as end-prog-short", "the same"),
    blocks: [
      WU(12),
      B("Steady", 1, [S(7200, 55, 65)]),
      B("Build", 1, [S(1800, 65, 75)]),
      CD(8),
    ],
  },
  {
    id: "end-torque-short",
    name: "Short Endurance with Torque",
    purpose: "aerobic_base",
    family: "torque",
    why: "Big-gear, low-cadence efforts inside an easy ride — force without intensity.",
    source: conv(
      "low-cadence strength-endurance work is widespread convention, and its distinct effect over the same work at self-selected cadence is not established",
      "a trial comparing low-cadence blocks against matched-load riding at free cadence"
    ),
    blocks: [
      WU(6),
      B("Torque", 2, [S(240, 60, 70, { rpm: 55 }), S(150, 50, 60)]),
      BODY(10, 55, 65),
      CD(5),
    ],
  },
  {
    id: "end-torque-mid",
    name: "Endurance with Torque",
    purpose: "aerobic_base",
    family: "torque",
    why: "The same torque work with a real endurance ride behind it.",
    source: conv("as end-torque-short", "the same"),
    blocks: [
      WU(6),
      B("Torque", 2, [S(240, 60, 70, { rpm: 55 }), S(150, 50, 60)]),
      BODY(30, 55, 65),
      CD(5),
    ],
  },
  {
    id: "end-torque-long",
    name: "Endurance with Torque, Extended",
    purpose: "aerobic_base",
    family: "torque",
    why: "Three longer torque blocks, then an hour steady.",
    source: conv("as end-torque-short", "the same"),
    blocks: [
      WU(8),
      B("Torque", 3, [S(300, 60, 70, { rpm: 55 }), S(180, 50, 60)]),
      BODY(60, 55, 65),
      CD(6),
    ],
  },
  {
    id: "end-torque-xl",
    name: "Long Endurance with Torque",
    purpose: "aerobic_base",
    family: "torque",
    why: "Torque work early, then two hours of aerobic riding.",
    source: conv("as end-torque-short", "the same"),
    blocks: [
      WU(8),
      B("Torque", 3, [S(300, 60, 70, { rpm: 55 }), S(180, 50, 60)]),
      BODY(120, 55, 65),
      CD(6),
    ],
  },

  // long: two families answered all 253 minutes. Tempo blocks and late
  // efforts are different stimuli from steady riding and from surges —
  // sustained moderate work, and hard work on already-tired legs.
  {
    id: "long-tempo-short",
    name: "Long Ride with Tempo",
    purpose: "long",
    family: "long-tempo",
    why: "Steady riding, then a sustained tempo block in the second half.",
    source: conv(
      "placing tempo late in a long ride is convention; nothing here establishes that the same tempo work adapts differently for having endurance riding in front of it",
      "a trial comparing tempo blocks ridden fresh against the same blocks ridden after two hours"
    ),
    blocks: [
      WU(8),
      BODY(25, 55, 65),
      B("Tempo", 1, [S(600, 76, 85), S(300, 55, 60)]),
      CD(6),
    ],
  },
  {
    id: "long-tempo-mid",
    name: "Long Ride with Tempo, Extended",
    purpose: "long",
    family: "long-tempo",
    why: "Two tempo blocks behind a longer endurance body.",
    source: conv("as long-tempo-short", "the same"),
    blocks: [
      WU(10),
      BODY(35, 55, 65),
      B("Tempo", 2, [S(600, 76, 85), S(300, 55, 60)]),
      CD(8),
    ],
  },
  {
    id: "long-tempo-long",
    name: "Long Ride with Tempo, Long",
    purpose: "long",
    family: "long-tempo",
    why: "An hour steady, then three tempo blocks.",
    source: conv("as long-tempo-short", "the same"),
    blocks: [
      WU(12),
      BODY(60, 55, 65),
      B("Tempo", 3, [S(600, 76, 85), S(300, 55, 60)]),
      CD(8),
    ],
  },
  {
    id: "long-tempo-xl",
    name: "Long Ride with Tempo, Extended Long",
    purpose: "long",
    family: "long-tempo",
    why: "Two hours of endurance before the tempo work starts.",
    source: conv("as long-tempo-short", "the same"),
    blocks: [
      WU(12),
      BODY(120, 55, 65),
      B("Tempo", 3, [S(600, 76, 85), S(300, 55, 60)]),
      CD(8),
    ],
  },
  {
    id: "long-tempo-xxl",
    name: "Long Ride with Tempo, Longest",
    purpose: "long",
    family: "long-tempo",
    why: "The longest tempo-carrying ride the plan will ask for.",
    source: conv("as long-tempo-short", "the same"),
    blocks: [
      WU(12),
      BODY(180, 55, 65),
      B("Tempo", 3, [S(600, 76, 85), S(300, 55, 60)]),
      CD(8),
    ],
  },
  {
    id: "long-fatigue-short",
    name: "Long Ride, Efforts at the End",
    purpose: "long",
    family: "long-fatigue",
    why: "Hard efforts saved for the end, when the legs are already tired.",
    source: conv(
      "training durability by placing the hard work last is convention, and how much it adds over the same efforts ridden fresh is not established",
      "a trial measuring late-ride power after a durability block against a matched-load ride with the efforts at the front"
    ),
    blocks: [
      WU(8),
      BODY(25, 55, 65),
      B("Efforts", 2, [S(300, 88, 95), S(300, 55, 60)]),
      CD(6),
    ],
  },
  {
    id: "long-fatigue-mid",
    name: "Long Ride, Efforts at the End, Extended",
    purpose: "long",
    family: "long-fatigue",
    why: "Three efforts after forty minutes of steady riding.",
    source: conv("as long-fatigue-short", "the same"),
    blocks: [
      WU(10),
      BODY(40, 55, 65),
      B("Efforts", 3, [S(300, 88, 95), S(300, 55, 60)]),
      CD(8),
    ],
  },
  {
    id: "long-fatigue-long",
    name: "Long Ride, Efforts at the End, Long",
    purpose: "long",
    family: "long-fatigue",
    why: "Over an hour steady, then the efforts.",
    source: conv("as long-fatigue-short", "the same"),
    blocks: [
      WU(12),
      BODY(70, 55, 65),
      B("Efforts", 3, [S(300, 88, 95), S(300, 55, 60)]),
      CD(8),
    ],
  },
  {
    id: "long-fatigue-xl",
    name: "Long Ride, Efforts at the End, Extended Long",
    purpose: "long",
    family: "long-fatigue",
    why: "Two hours in the legs before the first effort.",
    source: conv("as long-fatigue-short", "the same"),
    blocks: [
      WU(12),
      BODY(120, 55, 65),
      B("Efforts", 3, [S(300, 88, 95), S(300, 55, 60)]),
      CD(8),
    ],
  },
  {
    id: "long-fatigue-xxl",
    name: "Long Ride, Efforts at the End, Longest",
    purpose: "long",
    family: "long-fatigue",
    why: "The longest durability ride the plan will ask for.",
    source: conv("as long-fatigue-short", "the same"),
    blocks: [
      WU(12),
      BODY(180, 55, 65),
      B("Efforts", 3, [S(300, 88, 95), S(300, 55, 60)]),
      CD(8),
    ],
  },

  // threshold: 27-97 and 115-120 sat at two families. A ladder and a
  // tempo-float set are different shapes from even blocks, sweet spot and
  // over-unders — the work is arranged differently, not merely renamed.
  {
    id: "thr-ladder-26",
    name: "Threshold Ladder 3-5-3",
    purpose: "threshold",
    family: "ladder",
    why: "Blocks that grow then shrink — the hardest one sits in the middle.",
    source: conv(
      "the ascending-descending block ladder is a convention for holding threshold work together when a single long block would not be completed; nothing establishes it adapts differently from equal work in even blocks",
      "a trial comparing a ladder against matched time-at-intensity in even blocks"
    ),
    blocks: [
      WU(6),
      B("Main set", 1, [
        S(180, 95, 100),
        S(120, 55, 60),
        S(300, 95, 100),
        S(120, 55, 60),
        S(180, 95, 100),
      ]),
      CD(5),
    ],
  },
  {
    id: "thr-ladder-32",
    name: "Threshold Ladder 4-6-4",
    purpose: "threshold",
    family: "ladder",
    why: "The same shape, a step longer at every rung.",
    source: conv("as thr-ladder-26", "the same"),
    blocks: [
      WU(8),
      B("Main set", 1, [
        S(240, 95, 100),
        S(120, 55, 60),
        S(360, 95, 100),
        S(120, 55, 60),
        S(240, 95, 100),
      ]),
      CD(5),
    ],
  },
  {
    id: "thr-ladder-40",
    name: "Threshold Ladder 5-8-5",
    purpose: "threshold",
    family: "ladder",
    why: "Three rungs topping out at eight minutes.",
    source: conv("as thr-ladder-26", "the same"),
    blocks: [
      WU(12),
      B("Main set", 1, [
        S(300, 95, 100),
        S(150, 55, 60),
        S(480, 95, 100),
        S(150, 55, 60),
        S(300, 95, 100),
      ]),
      CD(6),
    ],
  },
  {
    id: "thr-ladder-54",
    name: "Threshold Ladder 4-6-8-6-4",
    purpose: "threshold",
    family: "ladder",
    why: "Five rungs up to eight minutes and back down.",
    source: conv("as thr-ladder-26", "the same"),
    blocks: [
      WU(12),
      B("Main set", 1, [
        S(240, 95, 100),
        S(120, 55, 60),
        S(360, 95, 100),
        S(120, 55, 60),
        S(480, 95, 100),
        S(120, 55, 60),
        S(360, 95, 100),
        S(120, 55, 60),
        S(240, 95, 100),
      ]),
      CD(6),
    ],
  },
  {
    id: "thr-ladder-68",
    name: "Threshold Ladder 5-8-10-8-5",
    purpose: "threshold",
    family: "ladder",
    why: "Five rungs topping out at ten minutes.",
    source: conv("as thr-ladder-26", "the same"),
    blocks: [
      WU(14),
      B("Main set", 1, [
        S(300, 95, 100),
        S(150, 55, 60),
        S(480, 95, 100),
        S(150, 55, 60),
        S(600, 95, 100),
        S(150, 55, 60),
        S(480, 95, 100),
        S(150, 55, 60),
        S(300, 95, 100),
      ]),
      CD(8),
    ],
  },
  {
    id: "thr-ladder-79",
    name: "Threshold Ladder 6-10-12-10-6",
    purpose: "threshold",
    family: "ladder",
    why: "Fifty-four minutes at threshold, arranged so the longest block comes when the legs are warmest.",
    source: conv("as thr-ladder-26", "the same"),
    blocks: [
      WU(15),
      B("Main set", 1, [
        S(360, 95, 100),
        S(180, 55, 60),
        S(600, 95, 100),
        S(180, 55, 60),
        S(720, 95, 100),
        S(180, 55, 60),
        S(600, 95, 100),
        S(180, 55, 60),
        S(360, 95, 100),
      ]),
      CD(8),
    ],
  },
  {
    id: "thr-ladder-95",
    name: "Threshold Ladder 8-12-15-12-8",
    purpose: "threshold",
    family: "ladder",
    why: "A long ladder for a big threshold day.",
    source: conv("as thr-ladder-26", "the same"),
    blocks: [
      WU(18),
      B("Main set", 1, [
        S(480, 95, 100),
        S(180, 55, 60),
        S(720, 95, 100),
        S(180, 55, 60),
        S(900, 95, 100),
        S(180, 55, 60),
        S(720, 95, 100),
        S(180, 55, 60),
        S(480, 95, 100),
      ]),
      CD(10),
    ],
  },
  {
    id: "thr-ladder-112",
    name: "Threshold Ladder 10-15-20-15-10",
    purpose: "threshold",
    family: "ladder",
    why: "The longest ladder — eighty-two minutes at threshold.",
    source: conv("as thr-ladder-26", "the same"),
    blocks: [
      WU(21),
      B("Main set", 1, [
        S(600, 95, 100),
        S(180, 55, 60),
        S(900, 95, 100),
        S(180, 55, 60),
        S(1200, 95, 100),
        S(180, 55, 60),
        S(900, 95, 100),
        S(180, 55, 60),
        S(600, 95, 100),
      ]),
      CD(10),
    ],
  },
  {
    id: "thr-float-45",
    name: "Threshold Floats 2×8",
    purpose: "threshold",
    family: "float",
    why: "Eight minutes at threshold, then four at tempo rather than easy — the effort never fully drops.",
    source: conv(
      "floating the recovery at tempo rather than easy is a convention for raising the total work of a threshold session without lengthening it; how the float changes the adaptation is not established",
      "a trial comparing tempo floats against easy recoveries at matched time-at-threshold"
    ),
    blocks: [
      WU(14),
      B("Main set", 2, [S(480, 95, 100), S(240, 76, 82)]),
      CD(6),
    ],
  },
  {
    id: "thr-float-56",
    name: "Threshold Floats 3×8",
    purpose: "threshold",
    family: "float",
    why: "Three blocks with tempo floats between them.",
    source: conv("as thr-float-45", "the same"),
    blocks: [
      WU(12),
      B("Main set", 3, [S(480, 95, 100), S(240, 76, 82)]),
      CD(8),
    ],
  },
  {
    id: "thr-float-70",
    name: "Threshold Floats 4×8",
    purpose: "threshold",
    family: "float",
    why: "Four blocks — forty-eight minutes with no easy riding inside the set.",
    source: conv("as thr-float-45", "the same"),
    blocks: [
      WU(14),
      B("Main set", 4, [S(480, 95, 100), S(240, 76, 82)]),
      CD(8),
    ],
  },
  {
    id: "thr-float-86",
    name: "Threshold Floats 5×8",
    purpose: "threshold",
    family: "float",
    why: "Five blocks of the same shape.",
    source: conv("as thr-float-45", "the same"),
    blocks: [
      WU(16),
      B("Main set", 5, [S(480, 95, 100), S(240, 76, 82)]),
      CD(10),
    ],
  },
  {
    id: "thr-float-100",
    name: "Threshold Floats 6×8",
    purpose: "threshold",
    family: "float",
    why: "Six blocks — a large sub-threshold load.",
    source: conv("as thr-float-45", "the same"),
    blocks: [
      WU(18),
      B("Main set", 6, [S(480, 95, 100), S(240, 76, 82)]),
      CD(10),
    ],
  },
  {
    id: "thr-float-114",
    name: "Threshold Floats 7×8",
    purpose: "threshold",
    family: "float",
    why: "The longest float session the plan will ask for.",
    source: conv("as thr-float-45", "the same"),
    blocks: [
      WU(20),
      B("Main set", 7, [S(480, 95, 100), S(240, 76, 82)]),
      CD(10),
    ],
  },

  // vo2max: two families answered all 89 minutes. Micro-bursts and ramped
  // reps are different shapes from even 3-5 minute efforts, not renames.
  {
    id: "vo2-15-15-a",
    name: "VO₂max 15/15",
    purpose: "vo2max",
    family: "micro-burst",
    why: "Ten short bursts a set — hard enough to matter, short enough to repeat.",
    source: conv(
      "15/15 micro-intervals are a published training shape and the claim that they hold more time near VO2max than longer reps is model-based rather than measured on this athlete",
      "a trial measuring time above 90% VO2max in micro-intervals against 3-5 minute reps at matched work"
    ),
    blocks: [
      WU(12),
      B("Main set", 2, [
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(300, 50, 50),
      ]),
      CD(6),
    ],
  },
  {
    id: "vo2-15-15-b",
    name: "VO₂max 15/15, Three Sets",
    purpose: "vo2max",
    family: "micro-burst",
    why: "Three sets of the same bursts.",
    source: conv("as vo2-15-15-a", "the same"),
    blocks: [
      WU(14),
      B("Main set", 3, [
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(300, 50, 50),
      ]),
      CD(6),
    ],
  },
  {
    id: "vo2-15-15-c",
    name: "VO₂max 15/15, Four Sets",
    purpose: "vo2max",
    family: "micro-burst",
    why: "Forty bursts in four sets.",
    source: conv("as vo2-15-15-a", "the same"),
    blocks: [
      WU(12),
      B("Main set", 4, [
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(300, 50, 50),
      ]),
      CD(8),
    ],
  },
  {
    id: "vo2-15-15-d",
    name: "VO₂max 15/15, Five Sets",
    purpose: "vo2max",
    family: "micro-burst",
    why: "Five sets — a substantial micro-interval day.",
    source: conv("as vo2-15-15-a", "the same"),
    blocks: [
      WU(14),
      B("Main set", 5, [
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(300, 50, 50),
      ]),
      CD(8),
    ],
  },
  {
    id: "vo2-15-15-e",
    name: "VO₂max 15/15, Six Sets",
    purpose: "vo2max",
    family: "micro-burst",
    why: "Six sets of bursts.",
    source: conv("as vo2-15-15-a", "the same"),
    blocks: [
      WU(16),
      B("Main set", 6, [
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(300, 50, 50),
      ]),
      CD(10),
    ],
  },
  {
    id: "vo2-15-15-f",
    name: "VO₂max 15/15, Seven Sets",
    purpose: "vo2max",
    family: "micro-burst",
    why: "Seven sets behind a long build.",
    source: conv("as vo2-15-15-a", "the same"),
    blocks: [
      WU(20),
      B("Main set", 7, [
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(300, 50, 50),
      ]),
      CD(10),
    ],
  },
  {
    id: "vo2-15-15-g",
    name: "VO₂max 15/15, Eight Sets",
    purpose: "vo2max",
    family: "micro-burst",
    why: "The longest micro-interval session the plan will ask for.",
    source: conv("as vo2-15-15-a", "the same"),
    // WU(20), not the WU(22) this was first authored at. The warmup is the
    // flex step, so it sets the span: at 22 this reached 123 minutes and
    // began answering the 122-144 minute "vo2max" days a 17-20 h/week
    // triathlon plan produces — days the ceiling exists to refuse, because
    // a 144-minute session the engine labels vo2max is an endurance ride
    // with intervals in it. The triathlon guard caught it.
    blocks: [
      WU(20),
      B("Main set", 8, [
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(15, 120, 130),
        S(15, 50, 50),
        S(300, 50, 50),
      ]),
      CD(10),
    ],
  },
  {
    id: "vo2-ramp-a",
    name: "VO₂max Ramps 4×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    why: "Three-minute reps that get harder each minute — the last one is the point.",
    source: conv(
      "ramping each rep so it finishes hardest is convention, on the reasoning that the last minute is where the oxygen cost peaks; the shape is not established against a flat rep",
      "a trial comparing ramped reps against flat reps at matched average intensity"
    ),
    blocks: [
      WU(10),
      B("Main set", 4, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(6),
    ],
  },
  {
    id: "vo2-ramp-b",
    name: "VO₂max Ramps 5×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    why: "Five ramped reps.",
    source: conv("as vo2-ramp-a", "the same"),
    blocks: [
      WU(12),
      B("Main set", 5, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(6),
    ],
  },
  {
    id: "vo2-ramp-c",
    name: "VO₂max Ramps 6×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    why: "Six ramped reps.",
    source: conv("as vo2-ramp-a", "the same"),
    blocks: [
      WU(12),
      B("Main set", 6, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(8),
    ],
  },
  {
    id: "vo2-ramp-d",
    name: "VO₂max Ramps 7×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    why: "Seven ramped reps.",
    source: conv("as vo2-ramp-a", "the same"),
    blocks: [
      WU(14),
      B("Main set", 7, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(8),
    ],
  },
  {
    id: "vo2-ramp-e",
    name: "VO₂max Ramps 8×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    why: "Eight ramped reps — twenty-four minutes of work.",
    source: conv("as vo2-ramp-a", "the same"),
    blocks: [
      WU(16),
      B("Main set", 8, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(10),
    ],
  },
  {
    id: "vo2-ramp-f",
    name: "VO₂max Ramps 9×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    why: "The longest ramp session the plan will ask for.",
    source: conv("as vo2-ramp-a", "the same"),
    blocks: [
      WU(18),
      B("Main set", 9, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(10),
    ],
  },

  // The last five, authored at the measured thin edges rather than to round
  // the total up: aerobic_base 21-28, threshold 27-36 and vo2max 32-34 and
  // 92-120 were the only bands still answered by exactly three families.
  {
    id: "end-torque-mini",
    name: "Short Endurance with Torque",
    purpose: "aerobic_base",
    family: "torque",
    why: "Two short big-gear efforts on a brief easy ride.",
    source: conv("as end-torque-short", "the same"),
    blocks: [
      WU(4),
      B("Torque", 2, [S(120, 60, 70, { rpm: 55 }), S(90, 50, 60)]),
      BODY(9, 55, 65),
      CD(4),
    ],
  },
  {
    id: "thr-float-32",
    name: "Threshold Floats 2×5",
    purpose: "threshold",
    family: "float",
    why: "The float shape at its shortest — two five-minute blocks.",
    source: conv("as thr-float-45", "the same"),
    blocks: [
      WU(11),
      B("Main set", 2, [S(300, 95, 100), S(150, 76, 82)]),
      CD(5),
    ],
  },
  {
    id: "vo2-ramp-mini",
    name: "VO₂max Ramps 3×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    why: "Three ramped reps — the shortest VO₂max day of this shape.",
    source: conv("as vo2-ramp-a", "the same"),
    blocks: [
      WU(9),
      B("Main set", 3, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(5),
    ],
  },
  {
    id: "vo2-ramp-g",
    name: "VO₂max Ramps 10×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    why: "Ten ramped reps — thirty minutes of work.",
    source: conv("as vo2-ramp-a", "the same"),
    blocks: [
      WU(20),
      B("Main set", 10, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(10),
    ],
  },
  {
    id: "vo2-ramp-h",
    name: "VO₂max Ramps 13×3",
    purpose: "vo2max",
    family: "ramp-vo2",
    // WU(20) with CD(12), so the span tops out at exactly 120 — the vo2max
    // ceiling. See vo2-15-15-g: the warmup is the flex step, and a longer
    // one here would start answering the 122-144 minute days the ceiling
    // exists to refuse.
    why: "The longest ramp session the plan will ask for.",
    source: conv("as vo2-ramp-a", "the same"),
    blocks: [
      WU(20),
      B("Main set", 13, [
        S(60, 100, 106),
        S(60, 106, 112),
        S(60, 112, 120),
        S(180, 50, 50),
      ]),
      CD(12),
    ],
  },
];
